run:
  timeout: 5m
  allow-parallel-runners: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
  disable:
    - dupl          # Disable duplicate code detection (scaffolded test code)
    - lll           # Disable line length check
    - revive        # Disable revive (too strict for kubebuilder scaffolded code)
    - goconst       # Disable constant suggestions

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false

issues:
  exclude-rules:
    # Exclude test files from some linters
    - path: _test\.go
      linters:
        - dupl
        - goconst
        - errcheck
    # Exclude generated files
    - path: zz_generated
      linters:
        - all
    # Exclude kubebuilder markers from line length
    - source: "// \\+kubebuilder:"
      linters:
        - lll
  max-issues-per-linter: 0
  max-same-issues: 0
