run:
  timeout: 5m
  allow-parallel-runners: true

linters:
  # Disable all linters first, then enable specific ones
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false

issues:
  exclude-rules:
    # Exclude test files from errcheck
    - path: _test\.go
      linters:
        - errcheck
    # Exclude generated files
    - path: zz_generated
      linters:
        - errcheck
        - govet
  max-issues-per-linter: 0
  max-same-issues: 0
